# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i72sxZ3REpJ1QDF6OgdcJoKGLvEw-WDv
"""

# 1  -  CRIE UM SISTEMA QUE SOME 2  NUMEROS *
n1 = 10
n2 = 10
print(n1+n2)



# 2 - CRIE UM SISTEMA QUE IMPRIMA SEU NOME NA TELA

nome = "Lucio"
print(nome)

# 3 - CRIE UM SISTEMA QUE IMPRIMA SEU NOME E UM CUMPRIMENTO APÓS

nome2 = "Lucio"
comprimento = "Ola"
print(comprimento, nome2)


# 4 - CRIE UM SISTEMA QUE MULTIPLIQUE 2 NÚMEROS


n1 = 10
n2 = 10
print(n1*n2)